server:
  port: 50004
  
spring:
  application:
    name: catalog-ws
  profiles:
    active: local      
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console        
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: 
    initialization-mode: always   # always로 설정시 재기동 될때마다 schema, data 내용들로 초기화
    schema: classpath:h2/schema.sql 
    data: classpath:h2/data.sql
    
  redis:
    lettuce:
      timeout: 1000    # 10초 --> 1초
      shutdown-timeout: 100
      auto-reconnect: false
      pool:
        max-active: 1   # pool에 할당할수 있는 커넥션 최대수(default:8)
        max-idle: 1     # pool의 idle 커넥션 최대수(default:8)
        min-idle: 0     # pool의 idle 커넥션 최소수(default:0)
    host: localhost  # 
    port: 6379
    