drop table if exists users CASCADE;
create table users
(
   id bigint generated by default as identity,
   user_id   varchar(255),
   user_name varchar(255),
   age    integer ,
   height integer ,
   created_at date default CURRENT_TIMESTAMP(),
   primary key (id)
);